1002 폴더에 담아 배문규 스터디 3문제 PR합니다
lksa4e/Algoritm-Study pull request #125
Opened 2021-09-28 11:12 UTC by Baemung

죄송합니다 이제 좀 쉬겠습니다...

2021-09-28 13:51 UTC, capo-YoonJu requested changes
리뷰 완료했습니다~~ 너무 고생하셨습니다!!!

2021-09-28 13:51 UTC, capo-YoonJu commented on Java/1002/배문규/BaekOJ13460_배문규.java
> + * 역시 시뮬은 재밌긴한데 화가 많이 남
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 진짜 화가 많이 났습니다.. 삼성...!!

2021-09-28 13:51 UTC, capo-YoonJu commented on Java/1002/배문규/BaekOJ13460_배문규.java
> +			if(balls[4] > 10) return -1; // *중요 조건 : 10번을 초과하면 -1 리턴
아하 객체 안만드시고 배열 마지막 원소로 기울인 횟수를 넣어주셨군요

2021-09-28 13:51 UTC, capo-YoonJu commented on Java/1002/배문규/BaekOJ17472_배문규.java
> +						}
오 객체 생성 안하고 배열의 차원을 이용하여 두 섬 간 비용 저장하는 방법이 너무 새롭네요..!!!👍

2021-09-28 13:51 UTC, capo-YoonJu approved these changes

2021-09-28 14:06 UTC, lksa4e approved these changes
다리만들기는 못풀어서 나머지 두문제만 리뷰했습니다 ㅜ

2021-09-29 05:03 UTC, KimDaBin approved these changes
0928 문규님 PR 리뷰 완료했습니다👍

2021-09-29 05:03 UTC, KimDaBin commented on Java/1002/배문규/BaekOJ17472_배문규.java
> +		}
저도 처음에 대표자가 다른지로 모두 연결되어 있는지 판단했었는데 계속 틀려서 왜 그런가 했더니 크루스칼 알고리즘에서 if(find(v1) != find(v2))면 합쳐주는게 아니라 if(union(v1, v2))로 해줘서 그랬네요.. 문규님 코드를 보고 해답을 알게 되었습니다!!

2021-09-29 09:33 UTC, ykwon3357 commented on Java/1002/배문규/BaekOJ13460_배문규.java
> + * 역시 시뮬은 재밌긴한데 화가 많이 남
재미..? 문규님은 꼭 삼성가셔야겠군요 👍  저는 화만나네요 시뮬은..

2021-09-29 09:34 UTC, ykwon3357 commented on Java/1002/배문규/BaekOJ17471_배문규.java
> +		}
아하 -처리한 것을 이렇게 쓰는군요 좋은 아이디어입니다 👍

2021-09-29 09:35 UTC, ykwon3357 commented on Java/1002/배문규/BaekOJ17472_배문규.java
> +	static PriorityQueue<int[]> pq = new PriorityQueue<int[]>((a, b)->a[2]-b[2]);
오 이게되네요?? 생각도 못했습니다 ㅋㅋ 👍

2021-09-30 12:13 UTC, lksa4e approved these changes

2021-09-30 12:13 UTC, lksa4e commented on Java/1002/배문규/BaekOJ17472_배문규.java
> +	static PriorityQueue<int[]> pq = new PriorityQueue<int[]>((a, b)->a[2]-b[2]);
오오 좋은 방법 알게되었습니다! 👍

2021-09-30 13:14 UTC, rudguq439 approved these changes
문규님 코드리뷰 완료! 아프신데 문제 푸시느라 진짜 고생하셨습니다...

2021-09-30 13:14 UTC, rudguq439 commented on Java/1002/배문규/BaekOJ13460_배문규.java
> + * 역시 시뮬은 재밌긴한데 화가 많이 남
ㅋㅋㅋㅋㅋ 시뮬 사실 조금 재밌는 것 같기도 합니다

2021-09-30 13:14 UTC, rudguq439 commented on Java/1002/배문규/BaekOJ17471_배문규.java
> + * 버그없이 디테일하게 구현하기까지는 은근 까다로웠음
맞아요 아이디어는 금방 떠올랐는데, 시뮬은 항상 구현하기가 까다로운 것 같습니다.

2021-09-30 13:14 UTC, rudguq439 commented on Java/1002/배문규/BaekOJ17471_배문규.java
> +		}
공간도 아끼는 신박한 방법이네요..! 신기합니다 👍

2021-09-30 13:14 UTC, rudguq439 commented on Java/1002/배문규/BaekOJ17472_배문규.java
> + * 1. BFS로 섬을 2부터 ++해서 라벨링해서 서로 구분해 줌
저는 섬을 1번부터 이름 붙여야겠다 하고 강박적으로 하려해서 섬을 -1로 커버해주고 1번 라벨링 해줬는데, 그냥 그럴 필요 없이 2번부터 라벨링해주면 되는 거였네요

2021-09-30 13:14 UTC, rudguq439 commented on Java/1002/배문규/BaekOJ17472_배문규.java
> +	static PriorityQueue<int[]> pq = new PriorityQueue<int[]>((a, b)->a[2]-b[2]);
오 람다식 오랜만에 보네요... 한참 안써서 까먹었는데 다시 상기시켜주셔서 감사합니다 ㅋㅋㅋ

2021-10-01 01:09 UTC, merged